### ISSUE TITLE
Every icon/text is glitching blue with recent catacomb

### ISSUE THREAD

**Issue by kchibisov** [catacombing/epitaph#23]
Each icon I have in epitaph is just blue and glitches when things move around (like sliding). I'd assume incorrect rendering is due to opaque regions.

Everything was stock.

commit used: f1efc6d3fc5c77f97d1ee61878b00e16fb6a3662

**Comment by chrisduerr** [comment]
Could you try mesa 23.0.3? This sounds like a recent mesa bug I've encountered too.

**Comment by chrisduerr** [comment]
https://gitlab.freedesktop.org/mesa/mesa/-/issues/9487
